import type { StepId } from "./step-config";
import type { DepartmentId, SimConfig, StationConfig } from "./types";

const DEPT_1: DepartmentId = "dept-1";
const DEPT_2: DepartmentId = "dept-2";
const DEPT_3: DepartmentId = "dept-3";

const defaultStations: StationConfig[] = [
	{
		id: "s1",
		departmentId: DEPT_1,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s2",
		departmentId: DEPT_2,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s3",
		departmentId: DEPT_3,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s4",
		departmentId: DEPT_1,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s5",
		departmentId: DEPT_2,
		cycleTime: 2100,
		cycleVariance: 210,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s6",
		departmentId: DEPT_3,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s7",
		departmentId: DEPT_1,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s8",
		departmentId: DEPT_2,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s9",
		departmentId: DEPT_3,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
];

const baseConfig: Omit<SimConfig, "stepId" | "seed" | "stations"> = {
	simTicksPerSecond: 20,
	speed: 10,
	batchSize: 4,
	arrivalRateMs: 2000,
	pushOrPull: "push",
	defectProbability: 0.65,
	redBins: false,
	redBinsAtAllStations: false,
	layoutMode: "departments",
	trainingEffectiveness: 0.5,
	reworkSendsBack: true,
	reworkTicks: 9,
	revenuePerItem: 1500,
	laborCostPerTickPerEmployee: 3,
	inventoryCostPerItemPerTick: 2,
	materialCostPerItem: 100,
	defectCostCustomerShipped: 50,
	andonEnabled: false,
	andonPauseTicks: 25,
	travelTicksBetweenStations: 3,
	marketChangeIntervalTicks: null,
	marketChangeAutoIntervalMs: 20000,
	initialInvestment: 100000,
	managerReworkEnabled: false,
	managerReworkProbability: 0.6,
};

export interface StepPreset {
	config: Partial<SimConfig>;
	enabledControls: {
		batchSize: boolean;
		pushPull: boolean;
		wipLimit: boolean;
		defectProbability: boolean;
		trainingEffectiveness: boolean;
		cycleVariance: boolean;
		cycleTime: boolean;
		tickSpeed: boolean;
		andon: boolean;
		layoutMode: boolean;
		marketChange: boolean;
		blueBins: boolean;
	};
}

const taktStations: StationConfig[] = [
	{
		id: "s1",
		departmentId: DEPT_1,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s2",
		departmentId: DEPT_2,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s3",
		departmentId: DEPT_3,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s4",
		departmentId: DEPT_1,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s5a",
		departmentId: DEPT_2,
		cycleTime: 1050,
		cycleVariance: 105,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s5b",
		departmentId: DEPT_2,
		cycleTime: 1050,
		cycleVariance: 105,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s6",
		departmentId: DEPT_3,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s7",
		departmentId: DEPT_1,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s8",
		departmentId: DEPT_2,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
	{
		id: "s9",
		departmentId: DEPT_3,
		cycleTime: 900,
		cycleVariance: 90,
		capacity: 1,
		bufferBefore: 5,
		bufferAfter: 5,
		batchSize: 6,
		wipLimit: 50,
	},
];

export const STEP_PRESETS: Record<StepId, StepPreset> = {
	intro: {
		config: {
			...baseConfig,
		},
		enabledControls: {
			batchSize: false,
			pushPull: false,
			wipLimit: false,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: false,
			cycleTime: false,
			tickSpeed: true,
			andon: false,
			layoutMode: false,
			marketChange: false,
			blueBins: false,
		},
	},
	"step-1": {
		config: {
			...baseConfig,
			redBins: true,
			reworkSendsBack: false,
		},
		enabledControls: {
			batchSize: false,
			pushPull: false,
			wipLimit: false,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: false,
			cycleTime: false,
			tickSpeed: true,
			andon: false,
			layoutMode: false,
			marketChange: true,
			blueBins: false,
		},
	},
	"step-2": {
		config: {
			...baseConfig,
			redBins: true,
			defectProbability: 0.2,
			redBinsAtAllStations: true,
			andonEnabled: false,
		},
		enabledControls: {
			batchSize: false,
			pushPull: false,
			wipLimit: false,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: false,
			cycleTime: false,
			tickSpeed: true,
			andon: false,
			layoutMode: false,
			marketChange: true,
			blueBins: false,
		},
	},
	"step-3": {
		config: {
			...baseConfig,
			redBins: true,
			defectProbability: 0.2,
			redBinsAtAllStations: true,
			andonEnabled: true,
			managerReworkEnabled: true,
		},
		enabledControls: {
			batchSize: false,
			pushPull: false,
			wipLimit: false,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: false,
			cycleTime: false,
			tickSpeed: true,
			andon: true,
			layoutMode: false,
			marketChange: true,
			blueBins: false,
		},
	},
	"step-4": {
		config: {
			...baseConfig,
			redBins: true,
			defectProbability: 0.2,
			redBinsAtAllStations: true,
			andonEnabled: true,
			jidokaLineStop: true,
			andonPauseTicks: 25,
			managerReworkEnabled: true,
		},
		enabledControls: {
			batchSize: false,
			pushPull: false,
			wipLimit: false,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: false,
			cycleTime: false,
			tickSpeed: true,
			andon: true,
			layoutMode: false,
			marketChange: true,
			blueBins: false,
		},
	},
	"step-5": {
		config: {
			...baseConfig,
			redBins: true,
			defectProbability: 0.2,
			redBinsAtAllStations: true,
			andonEnabled: true,
			jidokaLineStop: true,
			andonPauseTicks: 25,
			layoutMode: "flow",
			travelTicksBetweenStations: 0,
			managerReworkEnabled: true,
		},
		enabledControls: {
			batchSize: false,
			pushPull: false,
			wipLimit: false,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: false,
			cycleTime: false,
			tickSpeed: true,
			andon: true,
			layoutMode: true,
			marketChange: true,
			blueBins: false,
		},
	},
	"step-6": {
		config: {
			...baseConfig,
			redBins: true,
			defectProbability: 0.2,
			redBinsAtAllStations: true,
			andonEnabled: true,
			jidokaLineStop: true,
			andonPauseTicks: 25,
			layoutMode: "flow",
			travelTicksBetweenStations: 6,
			pushOrPull: "pull",
			managerReworkEnabled: true,
		},
		enabledControls: {
			batchSize: false,
			pushPull: true,
			wipLimit: true,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: false,
			cycleTime: false,
			tickSpeed: true,
			andon: true,
			layoutMode: true,
			marketChange: true,
			blueBins: true,
		},
	},
	"step-7": {
		config: {
			...baseConfig,
			redBins: true,
			defectProbability: 0.2,
			redBinsAtAllStations: true,
			andonEnabled: true,
			jidokaLineStop: true,
			andonPauseTicks: 25,
			layoutMode: "flow",
			travelTicksBetweenStations: 6,
			pushOrPull: "pull",
			stations: taktStations,
			managerReworkEnabled: true,
		},
		enabledControls: {
			batchSize: false,
			pushPull: true,
			wipLimit: true,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: true,
			cycleTime: false,
			tickSpeed: true,
			andon: true,
			layoutMode: true,
			marketChange: true,
			blueBins: true,
		},
	},
	"step-8": {
		config: {
			...baseConfig,
			batchSize: 1,
			redBins: true,
			redBinsAtAllStations: true,
			andonEnabled: true,
			jidokaLineStop: true,
			andonPauseTicks: 25,
			layoutMode: "flow",
			travelTicksBetweenStations: 6,
			pushOrPull: "pull",
			managerReworkEnabled: true,
			stations: taktStations.map((s) => ({
				...s,
				batchSize: 1,
				cycleVariance: Math.round(s.cycleTime * 0.4),
			})),
		},
		enabledControls: {
			batchSize: false,
			pushPull: true,
			wipLimit: true,
			defectProbability: false,
			trainingEffectiveness: false,
			cycleVariance: true,
			cycleTime: false,
			tickSpeed: true,
			andon: true,
			layoutMode: true,
			marketChange: true,
			blueBins: true,
		},
	},
};

export function getInitialConfig(stepId: StepId, seed: number): SimConfig {
	const preset = STEP_PRESETS[stepId];
	const effective = preset ?? STEP_PRESETS.intro;
	const stations = effective.config.stations ?? defaultStations;
	return {
		...baseConfig,
		...effective.config,
		stations: stations.map((s) => ({ ...s })),
		stepId,
		seed,
	};
}
