/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimRouteImport } from './routes/sim'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimIndexRouteImport } from './routes/sim/index'
import { Route as SimStep8RouteImport } from './routes/sim/step-8'
import { Route as SimStep7RouteImport } from './routes/sim/step-7'
import { Route as SimStep6RouteImport } from './routes/sim/step-6'
import { Route as SimStep5RouteImport } from './routes/sim/step-5'
import { Route as SimStep4RouteImport } from './routes/sim/step-4'
import { Route as SimStep3RouteImport } from './routes/sim/step-3'
import { Route as SimStep2RouteImport } from './routes/sim/step-2'
import { Route as SimStep1RouteImport } from './routes/sim/step-1'

const SimRoute = SimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimIndexRoute = SimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimRoute,
} as any)
const SimStep8Route = SimStep8RouteImport.update({
  id: '/step-8',
  path: '/step-8',
  getParentRoute: () => SimRoute,
} as any)
const SimStep7Route = SimStep7RouteImport.update({
  id: '/step-7',
  path: '/step-7',
  getParentRoute: () => SimRoute,
} as any)
const SimStep6Route = SimStep6RouteImport.update({
  id: '/step-6',
  path: '/step-6',
  getParentRoute: () => SimRoute,
} as any)
const SimStep5Route = SimStep5RouteImport.update({
  id: '/step-5',
  path: '/step-5',
  getParentRoute: () => SimRoute,
} as any)
const SimStep4Route = SimStep4RouteImport.update({
  id: '/step-4',
  path: '/step-4',
  getParentRoute: () => SimRoute,
} as any)
const SimStep3Route = SimStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => SimRoute,
} as any)
const SimStep2Route = SimStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => SimRoute,
} as any)
const SimStep1Route = SimStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => SimRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/sim': typeof SimRouteWithChildren
  '/sim/step-1': typeof SimStep1Route
  '/sim/step-2': typeof SimStep2Route
  '/sim/step-3': typeof SimStep3Route
  '/sim/step-4': typeof SimStep4Route
  '/sim/step-5': typeof SimStep5Route
  '/sim/step-6': typeof SimStep6Route
  '/sim/step-7': typeof SimStep7Route
  '/sim/step-8': typeof SimStep8Route
  '/sim/': typeof SimIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/sim/step-1': typeof SimStep1Route
  '/sim/step-2': typeof SimStep2Route
  '/sim/step-3': typeof SimStep3Route
  '/sim/step-4': typeof SimStep4Route
  '/sim/step-5': typeof SimStep5Route
  '/sim/step-6': typeof SimStep6Route
  '/sim/step-7': typeof SimStep7Route
  '/sim/step-8': typeof SimStep8Route
  '/sim': typeof SimIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/sim': typeof SimRouteWithChildren
  '/sim/step-1': typeof SimStep1Route
  '/sim/step-2': typeof SimStep2Route
  '/sim/step-3': typeof SimStep3Route
  '/sim/step-4': typeof SimStep4Route
  '/sim/step-5': typeof SimStep5Route
  '/sim/step-6': typeof SimStep6Route
  '/sim/step-7': typeof SimStep7Route
  '/sim/step-8': typeof SimStep8Route
  '/sim/': typeof SimIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/sim'
    | '/sim/step-1'
    | '/sim/step-2'
    | '/sim/step-3'
    | '/sim/step-4'
    | '/sim/step-5'
    | '/sim/step-6'
    | '/sim/step-7'
    | '/sim/step-8'
    | '/sim/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/sim/step-1'
    | '/sim/step-2'
    | '/sim/step-3'
    | '/sim/step-4'
    | '/sim/step-5'
    | '/sim/step-6'
    | '/sim/step-7'
    | '/sim/step-8'
    | '/sim'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/sim'
    | '/sim/step-1'
    | '/sim/step-2'
    | '/sim/step-3'
    | '/sim/step-4'
    | '/sim/step-5'
    | '/sim/step-6'
    | '/sim/step-7'
    | '/sim/step-8'
    | '/sim/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SimRoute: typeof SimRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sim': {
      id: '/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof SimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim/': {
      id: '/sim/'
      path: '/'
      fullPath: '/sim/'
      preLoaderRoute: typeof SimIndexRouteImport
      parentRoute: typeof SimRoute
    }
    '/sim/step-8': {
      id: '/sim/step-8'
      path: '/step-8'
      fullPath: '/sim/step-8'
      preLoaderRoute: typeof SimStep8RouteImport
      parentRoute: typeof SimRoute
    }
    '/sim/step-7': {
      id: '/sim/step-7'
      path: '/step-7'
      fullPath: '/sim/step-7'
      preLoaderRoute: typeof SimStep7RouteImport
      parentRoute: typeof SimRoute
    }
    '/sim/step-6': {
      id: '/sim/step-6'
      path: '/step-6'
      fullPath: '/sim/step-6'
      preLoaderRoute: typeof SimStep6RouteImport
      parentRoute: typeof SimRoute
    }
    '/sim/step-5': {
      id: '/sim/step-5'
      path: '/step-5'
      fullPath: '/sim/step-5'
      preLoaderRoute: typeof SimStep5RouteImport
      parentRoute: typeof SimRoute
    }
    '/sim/step-4': {
      id: '/sim/step-4'
      path: '/step-4'
      fullPath: '/sim/step-4'
      preLoaderRoute: typeof SimStep4RouteImport
      parentRoute: typeof SimRoute
    }
    '/sim/step-3': {
      id: '/sim/step-3'
      path: '/step-3'
      fullPath: '/sim/step-3'
      preLoaderRoute: typeof SimStep3RouteImport
      parentRoute: typeof SimRoute
    }
    '/sim/step-2': {
      id: '/sim/step-2'
      path: '/step-2'
      fullPath: '/sim/step-2'
      preLoaderRoute: typeof SimStep2RouteImport
      parentRoute: typeof SimRoute
    }
    '/sim/step-1': {
      id: '/sim/step-1'
      path: '/step-1'
      fullPath: '/sim/step-1'
      preLoaderRoute: typeof SimStep1RouteImport
      parentRoute: typeof SimRoute
    }
  }
}

interface SimRouteChildren {
  SimStep1Route: typeof SimStep1Route
  SimStep2Route: typeof SimStep2Route
  SimStep3Route: typeof SimStep3Route
  SimStep4Route: typeof SimStep4Route
  SimStep5Route: typeof SimStep5Route
  SimStep6Route: typeof SimStep6Route
  SimStep7Route: typeof SimStep7Route
  SimStep8Route: typeof SimStep8Route
  SimIndexRoute: typeof SimIndexRoute
}

const SimRouteChildren: SimRouteChildren = {
  SimStep1Route: SimStep1Route,
  SimStep2Route: SimStep2Route,
  SimStep3Route: SimStep3Route,
  SimStep4Route: SimStep4Route,
  SimStep5Route: SimStep5Route,
  SimStep6Route: SimStep6Route,
  SimStep7Route: SimStep7Route,
  SimStep8Route: SimStep8Route,
  SimIndexRoute: SimIndexRoute,
}

const SimRouteWithChildren = SimRoute._addFileChildren(SimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  SimRoute: SimRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
